#**Basic operation in R**

###**Assignment - 01**

*-23913*

In [1]:
# Creating a matrix in R
A <- matrix(data=c(-3,2,893,0.17),nrow=2,ncol=2)
A # printing the matrix (by default col wise)

[,1] [,2]  
[1,] -3   893.00
[2,]  2     0.17

In [2]:
# Matrix Structure
matrix(data = c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=TRUE) # row wise
matrix(data = c(1,2,3,4,5,6),nrow=2,ncol=3,byrow=FALSE) # col wise

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [3]:
# Arranging multiple vectors in array
rbind(1:3,4:6) # 1:3 in first row and 4:6 in second row
cbind(c(1,4),c(2,5),c(3,6)) # 1,4 in col1; 2,5 in col2 and 3,6 in col3

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [4]:
# Dimension of a matrix
mymat <- rbind(c(1,3,4),5:3,c(100,20,90),11:13)
dim(mymat) # gives mat dimension
nrow(mymat) # no of rows
ncol(mymat) # no of cols
dim(mymat)[2] # same as no of cols


[1] 4 3

[1] 4

[1] 3

[1] 3

In [7]:
#Extracting elements of a matrix
A <- matrix(c(0.3,4.5,55.3,91,0.1,105.5,-4.2,8.2,27.9),nrow=3,ncol=3)
A

[,1] [,2]  [,3]
[1,]  0.3  91.0 -4.2
[2,]  4.5   0.1  8.2
[3,] 55.3 105.5 27.9

In [8]:
diag(x=A) # gives diagonal elements
# other operations with rows and cols
A[3,2]
A[,2]
A[2:3,]
A[,c(3,1)]
A[c(3,1),2:3]

[1]  0.3  0.1 27.9

[1] 105.5

[1]  91.0   0.1 105.5

[,1] [,2]  [,3]
[1,]  4.5   0.1  8.2
[2,] 55.3 105.5 27.9

[,1] [,2]
[1,] -4.2  0.3
[2,]  8.2  4.5
[3,] 27.9 55.3

[,1]  [,2]
[1,] 105.5 27.9
[2,]  91.0 -4.2

In [9]:
# Manipulating Matrix
A[,-2] # remove 2nd col
A[-1,3:2]
A[-1,-2]
A[-1,-c(2,3)]

[,1] [,2]
[1,]  0.3 -4.2
[2,]  4.5  8.2
[3,] 55.3 27.9

[,1] [,2] 
[1,]  8.2   0.1
[2,] 27.9 105.5

[,1] [,2]
[1,]  4.5  8.2
[2,] 55.3 27.9

[1]  4.5 55.3

In [10]:
B <- A # Storing matrix A in B
B

[,1] [,2]  [,3]
[1,]  0.3  91.0 -4.2
[2,]  4.5   0.1  8.2
[3,] 55.3 105.5 27.9

Other operations

In [11]:
B[2,] <- 1:3
B

[,1] [,2]  [,3]
[1,]  0.3  91.0 -4.2
[2,]  1.0   2.0  3.0
[3,] 55.3 105.5 27.9

In [13]:
B[c(1,3),2] <- 900
B

[,1] [,2] [,3]
[1,]  0.3 900  -4.2
[2,]  1.0   2   3.0
[3,] 55.3 900  27.9

In [14]:
B[,3] <- B[3,]
B

[,1] [,2] [,3] 
[1,]  0.3 900   55.3
[2,]  1.0   2  900.0
[3,] 55.3 900   27.9

In [15]:
B[c(1,3),c(1,3)] <- c(-7,7)
B

[,1] [,2] [,3]
[1,] -7   900   -7 
[2,]  1     2  900 
[3,]  7   900    7

In [16]:
B[c(1,3),2:1] <- c(65,-65,88,-88)
B

[,1] [,2] [,3]
[1,]  88   65   -7 
[2,]   1    2  900 
[3,] -88  -65    7

In [17]:
# Making diagonal elements as 0's
diag(x=B) <- rep(x=0,times=3)
B

[,1] [,2] [,3]
[1,]   0   65   -7 
[2,]   1    0  900 
[3,] -88  -65    0